const CHROME_ROOT_BOOKMARK_NODE_ID = "0"
const FIREFOX_ROOT_BOOKMARK_NODE_ID = "root________"
export const ROOT_BOOKMARK_NODE_ID =
  process.env.PLASMO_BROWSER === "firefox"
    ? FIREFOX_ROOT_BOOKMARK_NODE_ID
    : CHROME_ROOT_BOOKMARK_NODE_ID
